import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const jersey_15 = Jersey_15({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jersey_15.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
